### ISSUE TITLE
Presentation Requirements

### ISSUE THREAD

**Issue by shoc71** [shoc71/Restaurant-Roulette#4]
- [x] Elevator pitch: a one minute description of your application
- [x] Concept: What is your user story? What was your motivation for development?
- [x] Process: What were the technologies used? How were tasks and roles broken down and assigned? What challenges did you encounter? What were your successes?
- [ ] Demo: Show your stuff!
- [x] Directions for Future Development
- [x] Links to the deployed application and the GitHub repository

**Comment by TilesTwenty** [comment]
https://docs.google.com/presentation/d/10sai_5G-7A0pKbSIhdNIIZAkRHsuv-e8aqYteu_FNBw/edit?usp=sharing
